#!/bin/bash
# Regenerates manifest.js from images/gallery/<year>/ and books/<year>.md.
# The manifest is what makes the page work when it is opened straight from disk,
# where fetch() cannot read local files.
# Run it after dropping new photos or editing a book list:  ./make-manifest.sh
# Or let it run itself on every change:  fswatch -o images/gallery books | xargs -n1 -I{} ./make-manifest.sh

cd "$(dirname "$0")" || exit 1

{
echo "// Generated by make-manifest.sh - do not edit by hand."
echo "window.GALLERY = {"
for dir in images/gallery/*/; do
year=$(basename "$dir")
files=$(find "$dir" -maxdepth 1 -type f \
\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \) \
| sed 's|.*/||' | sort | sed 's|.*|"&"|' | paste -sd, -)
echo "\"$year\": [$files],"
done
echo "};"

echo "window.BOOKS = {"
for file in books/*.md; do
[ -e "$file" ] || continue
year=$(basename "$file" .md)
# same cleanup showBooks() does: drop # headings and blank lines, strip "- ", "* ", "1. " bullets
titles=$(sed -e 's/\r$//' "$file" \
| grep -v '^[[:space:]]*#' \
| sed -E 's/^[[:space:]]*([-*+]|[0-9]+\.)[[:space:]]+//' \
| sed -e 's/[[:space:]]*$//' -e 's/^[[:space:]]*//' \
| grep -v '^$' \
| sed -e 's|\\|\\\\|g' -e 's|"|\\"|g' -e 's|.*|"&"|' | paste -sd, -)
echo "\"$year\": [$titles],"
done
echo "};"
} > manifest.js

echo "wrote manifest.js"
