#!/bin/bash
# Regenerates manifest.js from images/gallery/<year>/ and the <year>.md files in
# books/, work/, and journal/.
# The manifest is what makes the page work when it is opened straight from disk,
# where fetch() cannot read local files.
# Run it after dropping new photos or editing a list:  ./make-manifest.sh
# Or let it run itself on every change:  fswatch -o images/gallery books work journal | xargs -n1 -I{} ./make-manifest.sh

cd "$(dirname "$0")" || exit 1

# Turns a directory of <year>.md files into a `window.<NAME> = {...}` block.
# Same cleanup the page does: drop # headings and blank lines, strip "- ", "* ",
# "1. " bullets, then quote each surviving line.
md_years(){
echo "window.$2 = {"
for file in "$1"/*.md; do
[ -e "$file" ] || continue
year=$(basename "$file" .md)
lines=$(sed -e 's/\r$//' "$file" \
| grep -v '^[[:space:]]*#' \
| sed -E 's/^[[:space:]]*([-*+]|[0-9]+\.)[[:space:]]+//' \
| sed -e 's/[[:space:]]*$//' -e 's/^[[:space:]]*//' \
| grep -v '^$' \
| sed -e 's|\\|\\\\|g' -e 's|"|\\"|g' -e 's|.*|"&"|' | paste -sd, -)
echo "\"$year\": [$lines],"
done
echo "};"
}

{
echo "// Generated by make-manifest.sh - do not edit by hand."
echo "window.GALLERY = {"
for dir in images/gallery/*/; do
year=$(basename "$dir")
files=$(find "$dir" -maxdepth 1 -type f \
\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \) \
| sed 's|.*/||' | sort | sed 's|.*|"&"|' | paste -sd, -)
echo "\"$year\": [$files],"
done
echo "};"

md_years books BOOKS
md_years work WORK
md_years journal JOURNAL

# Pixel dimensions, keyed "<year>/<file>". The gallery reserves each tile at the
# right shape before the photo arrives, so the grid never reflows mid-load.
# sips reads all of them in well under a second.
echo "window.PHOTO_SIZES = {"
find images/gallery -type f \
\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.webp' \) \
-print0 | xargs -0 sips -g pixelWidth -g pixelHeight 2>/dev/null \
| awk -v root="$PWD/images/gallery/" '
index($0, root) == 1 { key = substr($0, length(root) + 1); next }
/pixelWidth:/  { w = $2 }
/pixelHeight:/ { h = $2; gsub(/\\/, "\\\\", key); gsub(/"/, "\\\"", key); print "\"" key "\": [" w "," h "]," }'
echo "};"
} > manifest.js

echo "wrote manifest.js"
