// Generated by make-manifest.sh - do not edit by hand.
window.GALLERY = {
"2024": ["000009860021 copy.jpg","Screenshot 2026-01-10 at 11.48.19 PM copy.png","manWorking copy.jpg","marfa_street copy.jpeg"],
"2025": ["Screenshot 2025-02-08 at 11.33.51 AM.png","Screenshot 2026-01-10 at 11.47.36 PM.png"],
"2026": ["alley.jpeg","bikes.jpeg","coffee.jpeg","lunch.jpeg","mirrorSelfie29.jpeg","parisSelfie.jpeg","readingboat.png","road.jpeg","selfie.jpeg","skycar.JPG","trail.jpeg","walk.JPG"],
};
window.BOOKS = {
"2026": ["the ministry of time","dandelion wine","invisible cities","klara and the sun","sea of tranquility","stoner","monstrillio"],
};
